[application]
name = "smart-shopping-calculator"
default_platform = "web"

[web.app]
title = "Smart Shopping Calculator"

[web.watcher]
reload_html = true
watch_path = ["src", "assets"]

[web.resource]
style = []
script = []
